apiVersion: v1
kind: Namespace
metadata:
  name: quantuml
  labels:
    app.kubernetes.io/part-of: quantuml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantuml-models
  namespace: quantuml
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - path: /pqc(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: model-server-pqc
                port:
                  number: 80
          - path: /crypto(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: model-server-crypto
                port:
                  number: 80
          - path: /ddi(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: model-server-ddi
                port:
                  number: 80
